
version: '3.8'
services:
  client:
      image: techscreens:dev
      environment:
        - NODE_ENV=development
      volumes: 
        - node_modules:/usr/src/app/node_modules
        - .:/usr/src/app
      command: yarn dev
      ports:
        - 3000:3000
        - 8080:8080
      working_dir: /usr/src/app
volumes:
  nodemodules:
    external: true

