'use strict';


const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ScriptExtHtmlWebpackPlugin = require('script-ext-html-webpack-plugin');


module.exports = function (opts) {
  return {
    ...opts,

    // Add development plugins
    plugins: [
      new webpack.HotModuleReplacementPlugin(),

      new HtmlWebpackPlugin({
        inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
        template: './client/ui/index.html', // TODO: should be passable via getConfig
        filename: 'index.html',
      }),

      // new ScriptExtHtmlWebpackPlugin({
      //   module: /(workers|sw)/,
      // })
    ],
  };
};
