'use strict';


const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');

const isDev = process.env.NODE_ENV === 'development';

module.exports = function ({
  htmlPlugin = {},

  ...opts
}) {

  return {
    ...opts,

    // Add development plugins
    plugins: [
      isDev && new webpack.HotModuleReplacementPlugin(),

      new HtmlWebpackPlugin({
        inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
        filename: 'index.html',
        minify: !isDev && {
          collapseWhitespace: true,
          removeComments: true,
          removeRedundantAttributes: true,
          removeScriptTypeAttributes: true,
          removeStyleLinkTypeAttributes: true,
          useShortDoctype: true,
          minifyCSS: true,
          minifyJS: true
        },
        meta: {
          // https://github.com/joshbuchea/HEAD#meta
          viewport: 'width=device-width, initial-scale=1.0',
          charset: 'UTF-8',
          'application-name': 'Client UI'

        },
        ...htmlPlugin
      }),

      // new ScriptExtHtmlWebpackPlugin({
      //   module: /(workers|sw)/,
      // })
    ].filter(a => a),
  };
};
